### ISSUE TITLE
Error: Null is not an object

### ISSUE THREAD

**Issue by Akshay9882** [nikches/react-native-calendar#2]
i am using the component as shown in below code but it always gives error `null is not an object (evaluating this.state.date)`

I tried initializing state variable named `state` and assign it `date` value but error still exists.
...
var Calendar = require('react-native-calendar-component');

export default class proj extends Component {

  constructor(props) {
   super(props);
   this.state = {
     date: new Date()
   };
 }

  render() {
    return (
      <Calendar
    date={this.state.date}
    onPrevButtonPress={() => this.handlePrevButtonPress()}
    onNextButtonPress={() => this.handleNextButtonPress()}
    onDateSelect={(date) => this.handleDateSelect(date)} />
    );
  }
}

...

**Comment by nikches** [comment]
This example work fine for me (reac-native 0.40). 

```javascript
import React, { Component } from "react";
import Calendar   from "react-native-calendar-component";

export default class CalendarTest extends Component {
    constructor(props) {
        super(props);

        this.state = {
            date: new Date()
        };
    }

    handleNextButtonPress() {
        const date = new Date(this.state.date);
        date.setMonth(date.getMonth() + 1);
        this.setState({
            date
        });
    }

    handlePrevButtonPress() {
        const date = new Date(this.state.date);
        date.setMonth(date.getMonth() - 1);
        this.setState({
            date
        });
    }

    handleDateSelect(date) {
        alert(`clicked: ${this.state.date.toString()}`);
    }

    render() {
        return (
            <Calendar
                date={this.state.date}
                onPrevButtonPress={() => this.handlePrevButtonPress()}
                onNextButtonPress={() => this.handleNextButtonPress()}
                onDateSelect={(date) => this.handleDateSelect(date)} />
        );
    }
}
```

**Comment by Akshay9882** [comment]
Ok thanks there is no error now.

**Comment by ttson24** [comment]
but i have to error:
typeError:undefined is not object(evaluating '_react2.default.PropTypes.object')

**Comment by Rafael-Ramblas** [comment]
Samething here
